import type { Scene } from '@graphlearning/flow'

// §2 modern-java — the same job written twice, so the gap is seen rather than claimed. Left: the
// Java 8 bean most people picture when they hear "Java". Right: the Java 21 version. Two code cards
// side by side in a two-column group; both `hug`, because inside a diagram a card's width sets the
// whole composition's size and the CODE_MIN_COLS floor would only inflate it. Gridded rather than
// edged: an arrow between them would ride a label across the left card's text.
export const modernJava: Scene = {
  id: 'modern-java',
  padding: 0.12,
  nodes: [
    {
      id: 'then-now',
      label: 'The same type, 13 years apart',
      pattern: 'group',
      icon: 'gitbranch',
      cols: 2,
      children: [
        {
          id: 'java8',
          kind: 'code',
          filename: 'Order.java · Java 8',
          hug: true,
          label: [
            'public final class Order {',
            '  private final String id;',
            '  private final int qty;',
            '',
            '  public Order(String id, int qty) {',
            '    this.id = id;',
            '    this.qty = qty;',
            '  }',
            '',
            '  public String getId()  { return id; }',
            '  public int    getQty() { return qty; }',
            '',
            '  @Override public boolean equals(Object o) {',
            '    /* 8 more lines */',
            '  }',
            '  @Override public int hashCode() { /* ... */ }',
            '  @Override public String toString() { /* ... */ }',
            '}',
          ].join('\n'),
        },
        {
          id: 'java21',
          kind: 'code',
          filename: 'Order.java · Java 21',
          hug: true,
          label: [
            'record Order(String id, int qty) {}',
            '',
            '// equals, hashCode, toString,',
            '// accessors and the constructor',
            '// are all generated by the compiler.',
            '',
            'sealed interface Event',
            '    permits Placed, Shipped {}',
            '',
            'String describe(Event e) {',
            '  return switch (e) {',
            '    case Placed p  -> "placed "  + p.id();',
            '    case Shipped s -> "shipped " + s.id();',
            '  };            // no default needed',
            '}',
          ].join('\n'),
        },
      ],
    },
  ],
  edges: [],
}
